/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 pants.glb 
*/


import React, { useEffect, useRef, useState } from "react";

import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";
import { type } from "@testing-library/user-event/dist/type";

export function PantsModel(props) {
  const { nodes, materials } = useGLTF("/models/pants.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        name="HG_Chinos_Male001"
        castShadow
        receiveShadow
        geometry={nodes.HG_Chinos_Male001.geometry}
        material={materials[".HG_Chinos.002"]}
        material-color = {props.color}
        morphTargetDictionary={nodes.HG_Chinos_Male001.morphTargetDictionary}
        morphTargetInfluences={nodes.HG_Chinos_Male001.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/pants.glb");
