/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 person.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PersonModel(props) {
  const { nodes, materials } = useGLTF("/models/person.glb");


  return (
    <group {...props} dispose={null}>
      <mesh 
        name="HG_Body004"
        castShadow
        receiveShadow
        geometry={nodes.HG_Body004.geometry}
        material={materials[".Human.010"]}
        morphTargetDictionary={nodes.HG_Body004.morphTargetDictionary}
        morphTargetInfluences={nodes.HG_Body004.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/person.glb");
